<?php
// initial load data for BMC
$loadData = array(
		// If you add any Analyzers HERE you MUST update the win_generate_oracle_pre_post file in App.
		'analyzers' => array(
			array('id' => 1, 'name' => 'Explode Reference Contents', 'module' => 'reference_explode'),
			array('id' => 2, 'name' => 'Generate WAR File Table Of Contents', 'module' => 'warfile_content'),
			array('id' => 3, 'name' => 'Generate Windows DLL Version', 'module' => 'reference_md'),
			array('id' => 4, 'name' => 'Explode Zip File', 'module' => 'reference_explode_zip'),
		),
		'analyzer_properties' => array(
			array('analyzer_id' => '1', 'name' => 'strip_paths_yn', 'value' => 'n'),
			array('analyzer_id' => '1', 'name' => 'delete_solid_yn','value' => 'y'),
			array('analyzer_id' => '3', 'name' => 'run_action',     'value' => 'win_dll_version'),
			array('analyzer_id' => '3', 'name' => 'host_bridge',    'value' => '1'),
		),
		// If you add any Packs HERE you MUST update the win_generate_oracle_pre_post file in App.
		'packs' => array(
			array('id' => 1,   'name' => 'generic'),
			array('id' => 10,  'name' => 'amazon'),
			array('id' => 20,  'name' => 'apache_2'),
			array('id' => 23,  'name' => 'atlassian'),
			array('id' => 25,  'name' => 'biztalk_2006'),
			array('id' => 26,  'name' => 'biztalk_2009'),
			array('id' => 27,  'name' => 'biztalk_2010'),
			array('id' => 28,  'name' => 'citrix'),
			array('id' => 30,  'name' => 'bma'),
			array('id' => 31,  'name' => 'cvs'),
			array('id' => 35,  'name' => 'db2'),
			array('id' => 40,  'name' => 'f5'),
			array('id' => 45,  'name' => 'git'),
			array('id' => 47,  'name' => 'glassfish_3'),
			array('id' => 50,  'name' => 'hyper_v'),
			array('id' => 55,  'name' => 'ibm_mq'),
			array('id' => 60,  'name' => 'iis_7'),
			array('id' => 65,  'name' => 'iis_6'),
			array('id' => 70,  'name' => 'jboss_5'),
			array('id' => 80,  'name' => 'jboss_6'),
			array('id' => 85,  'name' => 'jetbrains'),
			array('id' => 90,  'name' => 'mercurial'),
			array('id' => 100, 'name' => 'mysql_5'),
			array('id' => 105, 'name' => 'nsh'),
			array('id' => 110, 'name' => 'oracle_11g'),
			array('id' => 120, 'name' => 'perforce'),
			array('id' => 130, 'name' => 'php_5'),
			array('id' => 140, 'name' => 'rational'),
			array('id' => 142, 'name' => 'sharepoint_2007'),
			array('id' => 143, 'name' => 'sharepoint_2010'),
			array('id' => 145, 'name' => 'sonatype'),
			array('id' => 150, 'name' => 'sqlserver_2008'),
			array('id' => 155, 'name' => 'ssh'),
			array('id' => 160, 'name' => 'subversion'),
			array('id' => 170, 'name' => 'tfs'),
			array('id' => 175, 'name' => 'tibco_bw'),
			array('id' => 180, 'name' => 'tomcat_6'),
			array('id' => 190, 'name' => 'tomcat_7'),
			array('id' => 200, 'name' => 'websphere_6'),
			array('id' => 210, 'name' => 'websphere_7'),
			array('id' => 220, 'name' => 'websphere_8'),
			array('id' => 230, 'name' => 'weblogic_10'),
			array('id' => 235, 'name' => 'vmware'),
			array('id' => 240, 'name' => 'vss'),
			array('id' => 245, 'name' => 'chef'),
			array('id' => 250, 'name' => 'puppet'),
			array('id' => 260, 'name' => 'docker'),

		),
		'cmaps' => array(
			array('pack_id' => 1,   'sequence' => 0, 'name' => '[Generic][Application][Requires]',        'value' => 'ignore'),
			array('pack_id' => 1,   'sequence' => 1, 'name' => '[Generic][Application][Provides]',        'value' => 'ignore'),
			array('pack_id' => 1,   'sequence' => 2, 'name' => '[Generic][Win][Registry][Key][Create]',   'value' => 'win_regkey_create'),
			array('pack_id' => 1,   'sequence' => 3, 'name' => '[Generic][Win][Registry][Key][Delete]',   'value' => 'win_regkey_delete'),
			array('pack_id' => 1,   'sequence' => 4, 'name' => '[Generic][Win][Registry][Value][Create]', 'value' => 'win_regprop_create'),
			array('pack_id' => 1,   'sequence' => 5, 'name' => '[Generic][Win][Registry][Value][Delete]', 'value' => 'win_regprop_delete'),
			array('pack_id' => 20,  'sequence' => 1, 'name' => '[Apache_2]',	                          'value' => 'apache_set_config'),
			array('pack_id' => 35,  'sequence' => 1, 'name' => '[DB2]',			                          'value' => 'db2_set_property'),
			array('pack_id' => 47,  'sequence' => 1, 'name' => '[GlassFish_3]',                           'value' => 'glassFish_set_property'),
			array('pack_id' => 55,  'sequence' => 1, 'name' => '[IBM_MQ]',                                'value' => 'IBMMQ_set_config'),
			array('pack_id' => 60,  'sequence' => 1, 'name' => '[IIS_7][AppPool][Property][Set]',         'value' => 'IIS_app_pool_set'),
			array('pack_id' => 60,  'sequence' => 2, 'name' => '[IIS_7][MACHINE',                         'value' => 'IIS_set_property'),
			array('pack_id' => 65,  'sequence' => 2, 'name' => '[IIS_6]',                                 'value' => 'IIS_set_property'),
			array('pack_id' => 70,  'sequence' => 1, 'name' => '[JBoss_5]',                               'value' => 'jboss_set_config'),
			array('pack_id' => 80,  'sequence' => 1, 'name' => '[JBoss_6]',                               'value' => 'jboss_set_config'),
			array('pack_id' => 100, 'sequence' => 0, 'name' => '[Mysql_5][Server][global]',               'value' => 'mysql_set_config_global'),
			array('pack_id' => 110, 'sequence' => 0, 'name' => '[Oracle_11g][Server]',                    'value' => 'oracle_set_property'),
			array('pack_id' => 130, 'sequence' => 0, 'name' => '[Php_5]',			                      'value' => 'php_set_config'),
			array('pack_id' => 150, 'sequence' => 0, 'name' => '[SQLServer_2008][Server]',                'value' => 'mssql_set_property'),
			array('pack_id' => 175, 'sequence' => 0, 'name' => '[TIBCO_BW]',                              'value' => 'TIBCO_set_config'),
			array('pack_id' => 180, 'sequence' => 0, 'name' => '[Tomcat_6]',                              'value' => 'tomcat_set_property'),
			array('pack_id' => 190, 'sequence' => 0, 'name' => '[Tomcat_7]',                              'value' => 'tomcat_set_property'),
			array('pack_id' => 200, 'sequence' => 0, 'name' => '[Websphere_6]',                           'value' => 'websphere_set_config'),
			array('pack_id' => 210, 'sequence' => 0, 'name' => '[Websphere_7]',                           'value' => 'websphere_set_config'),
			array('pack_id' => 220, 'sequence' => 0, 'name' => '[Websphere_8]',                           'value' => 'websphere_set_config'),
			array('pack_id' => 230, 'sequence' => 0, 'name' => '[WebLogic_10]',                           'value' => 'weblogic_set_config'),
		),
		// If you add any Scheds HERE you MUST update the win_generate_oracle_pre_post file in App.
		'scheds' => array(
			array('id' => 2, 'user_id' => 2, 'name' => 'Perform Internal System Cleanup',      'gmt_fire' => 1, 'active' => 'y', 'module' => 'garbage_collector',    'spec' => '30 0 * * 0'),
			array('id' => 3, 'user_id' => 2, 'name' => 'Archive Audit Logs',                   'gmt_fire' => 0, 'active' => 'n', 'module' => 'archive_audit_log',    'spec' => '0 6 1 1,4,7,10 *'),
			array('id' => 4, 'user_id' => 2, 'name' => 'Prune Process Logs',                   'gmt_fire' => 0, 'active' => 'y', 'module' => 'prune_task_feed',      'spec' => '0 3 * * 2'),
			array('id' => 5, 'user_id' => 2, 'name' => 'Prune Instance Logs',                  'gmt_fire' => 0, 'active' => 'y', 'module' => 'prune_instance_feed',  'spec' => '0 4 * * 3'),
			array('id' => 6, 'user_id' => 2, 'name' => 'Purge Old System Processes',           'gmt_fire' => 0, 'active' => 'y', 'module' => 'purge_system_process', 'spec' => '0 1 * * 3,6'),
			array('id' => 7, 'user_id' => 2, 'name' => 'Expire Old Instances Weekly',          'gmt_fire' => 0, 'active' => 'y', 'module' => 'expire_instance',      'spec' => '0 0 * * 0'),
			array('id' => 8, 'user_id' => 2, 'name' => 'Sync All Managed Channels Each Night', 'gmt_fire' => 0, 'active' => 'n', 'module' => 'sync_all_blueprint',   'spec' => '30 3 * * *'),
			array('id' => 9, 'user_id' => 2, 'name' => 'Collect System Statistics',            'gmt_fire' => 1, 'active' => 'y', 'module' => 'system_stat',          'spec' => '10 22 * * 1,4'),
			array('id' => 11, 'user_id' => 2, 'name' => 'Prune Files On Shared Drive',         'gmt_fire' => 0, 'active' => 'n', 'module' => 'prune_shared_drive',   'spec' => '0 0 25 * 0'),

		),
		'sched_properties' => array(
			array('sched_id' => '3', 'name' => 'archive_lang',      'value' => 'eng'),	// archive_audit_log
			array('sched_id' => '3', 'name' => 'archive_path',      'value' => '/tmp'),
			array('sched_id' => '3', 'name' => 'older_than_days',   'value' => '120'),
			array('sched_id' => '4', 'name' => 'older_than_days',   'value' => '60'),	// prune_task_feed
			array('sched_id' => '5', 'name' => 'older_than_days',   'value' => '60'),	// prune_instance_feed
			array('sched_id' => '5', 'name' => 'prune_reponame',    'value' => ''),
			array('sched_id' => '6', 'name' => 'older_than_days',   'value' => '10'),	// purge_system_process
			array('sched_id' => '7', 'name' => 'older_than_days',   'value' => '30'),	// expire_instance
			array('sched_id' => '7', 'name' => 'keep_at_least',     'value' => '5'),
			array('sched_id' => '7', 'name' => 'expire_reponame',   'value' => ''),
			array('sched_id' => '9', 'name' => 'days_keep',         'value' => '180'),	// system_stat
			array('sched_id' => '11','name' => 'older_than_days',   'value' => '30'), 	// prune_shared_drive
			array('sched_id' => '11','name' => 'prune_bridge',      'value' => ''), 		// prune_shared_drive
			array('sched_id' => '11','name' => 'prune_rem_storage', 'value' => ''), 		// prune_shared_drive
		),
		'renores' => array(
			array('pack_id' => 2, 'platform_id' => 0, 'pattern' => '/LogFormat/'),
			array('pack_id' => 8, 'platform_id' => 0, 'pattern' => '/^timestamp/'),
			array('pack_id' => 8, 'platform_id' => 0, 'pattern' => '/^pseudo_thread_id/'),
			array('pack_id' => 8, 'platform_id' => 110, 'pattern' => '/^timestamp/'),
			array('pack_id' => 8, 'platform_id' => 110, 'pattern' => '/^pseudo_thread_id/'),
			array('pack_id' => 16, 'platform_id' => 0, 'pattern' => 'path:/\[web.xml]\[web-app]\[mime-mapping]/i'),
			array('pack_id' => 17, 'platform_id' => 0, 'pattern' => 'path:/\[web.xml]\[web-app]\[mime-mapping]/i'),
			array('pack_id' => 16, 'platform_id' => 110, 'pattern' => 'path:/\[web.xml]\[web-app]\[mime-mapping]/i'),
			array('pack_id' => 17, 'platform_id' => 110, 'pattern' => 'path:/\[web.xml]\[web-app]\[mime-mapping]/i'),
		),
		// If you add any Platforms HERE you MUST update the win_generate_oracle_pre_post file in App.
		'platform' => array(
			array('id' => 1,  'name' => 'Asset'),
			array('id' => 2,  'name' => 'Console'),
			array('id' => 3,  'name' => 'Build'),
			array('id' => 4,  'name' => 'Analyzer'),
			array('id' => 5,  'name' => 'Virtual'),
			array('id' => 6,  'name' => 'Auth'),
			array('id' => 7,  'name' => 'LoadBal'),
			array('id' => 8,  'name' => 'Config'),
			array('id' => 9,  'name' => 'Schedule'),
			array('id' => 10, 'name' => 'Target'),
			array('id' => 110,'name' => 'Windows-x86'),	// these MUST stay at their current numbers
			array('id' => 111,'name' => 'Windows-x64'),	// there is code that checks this

			array('id' => 200,'name' => 'DarwinOSX10-i386'),
			array('id' => 201,'name' => 'DarwinOSX10-x86_64'),

			array('id' => 300,'name' => 'LinuxRHEL4-x86_64'),
			array('id' => 301,'name' => 'LinuxRHEL4-i386'),
			array('id' => 310,'name' => 'LinuxRHEL5-x86_64'),
			array('id' => 311,'name' => 'LinuxRHEL5-i386'),
			array('id' => 312,'name' => 'LinuxRHEL6-x86_64'),
			array('id' => 313,'name' => 'LinuxRHEL6-i386'),
			array('id' => 320,'name' => 'LinuxSuSE10-x86_64'),
			array('id' => 321,'name' => 'LinuxSuSE10-i386'),

			array('id' => 400,'name' => 'SunOS5-i386'),
			array('id' => 410,'name' => 'SunOS5-sparc'),

			array('id' => 500,'name' => 'AIX5-powerpc'),
			array('id' => 510,'name' => 'AIX'),

			array('id' => 600,'name' => 'HP-UX11'),
			array('id' => 610,'name' => 'HP-UX11-Itanium'),
		),
		'platstring' => array(
			array('platform_id' => 110, 'pattern' => '/Windows/'),
			array('platform_id' => 110, 'pattern' => '/32-bit/'),
			array('platform_id' => 111, 'pattern' => '/Windows/'),
			array('platform_id' => 111, 'pattern' => '/64-bit/'),

			array('platform_id' => 200, 'pattern' => '/Darwin/'),
			array('platform_id' => 200, 'pattern' => '/i386/'),
			array('platform_id' => 200, 'pattern' => '/OSX10/'),
			array('platform_id' => 201, 'pattern' => '/Darwin/'),
			array('platform_id' => 201, 'pattern' => '/x86_64/'),
			array('platform_id' => 201, 'pattern' => '/OSX10/'),

			array('platform_id' => 300, 'pattern' => '/Linux/'),
			array('platform_id' => 300, 'pattern' => '/x86_64/'),
			array('platform_id' => 300, 'pattern' => '/RHEL4/'),
			array('platform_id' => 301, 'pattern' => '/Linux/'),
			array('platform_id' => 301, 'pattern' => '/i386/'),
			array('platform_id' => 301, 'pattern' => '/RHEL4/'),

			array('platform_id' => 310, 'pattern' => '/Linux/'),
			array('platform_id' => 310, 'pattern' => '/x86_64/'),
			array('platform_id' => 310, 'pattern' => '/RHEL5/'),
			array('platform_id' => 311, 'pattern' => '/Linux/'),
			array('platform_id' => 311, 'pattern' => '/i386/'),
			array('platform_id' => 311, 'pattern' => '/RHEL5/'),
			array('platform_id' => 312, 'pattern' => '/Linux/'),
			array('platform_id' => 312, 'pattern' => '/x86_64/'),
			array('platform_id' => 312, 'pattern' => '/RHEL6/'),
			array('platform_id' => 313, 'pattern' => '/Linux/'),
			array('platform_id' => 313, 'pattern' => '/i386/'),
			array('platform_id' => 313, 'pattern' => '/RHEL6/'),

			array('platform_id' => 320, 'pattern' => '/Linux/'),
			array('platform_id' => 320, 'pattern' => '/x86_64/'),
			array('platform_id' => 320, 'pattern' => '/SuSE10/'),
			array('platform_id' => 321, 'pattern' => '/Linux/'),
			array('platform_id' => 321, 'pattern' => '/i386/'),
			array('platform_id' => 321, 'pattern' => '/SuSE10/'),

			array('platform_id' => 400, 'pattern' => '/SunOS/'),
			array('platform_id' => 400, 'pattern' => '/i386/'),
			array('platform_id' => 410, 'pattern' => '/SunOS/'),
			array('platform_id' => 410, 'pattern' => '/sparc/'),

			array('platform_id' => 500, 'pattern' => '/AIX5/'),
			array('platform_id' => 510, 'pattern' => '/AIX/'),

			array('platform_id' => 600, 'pattern' => '/HP-UX11/'),
			array('platform_id' => 600, 'pattern' => '/9000/'),
			array('platform_id' => 610, 'pattern' => '/HP-UX11/'),
			array('platform_id' => 610, 'pattern' => '/ia64/'),
		),
		'bridge' => array(
			array('hostname' => 'localhost', 'despatcher' => 'nsh://localhost', 'platform' => 'Unknown', 'remote_platform' => '0'),
		),
		'bridge_role' => array(
			array('role_id' => '0', 'bridge_id' => '1'),
		),
		'platform_properties' => array(
			array('platform_id' => 10, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 10, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 10, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 10, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 10, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 10, 'name' => 'RM', 'value' => '/bin/rm'),
			array('platform_id' => 11, 'name' => 'TYPE', 'value' => 'type'),
			array('platform_id' => 11, 'name' => 'DIR', 'value' => 'dir'),
			array('platform_id' => 11, 'name' => 'DEL', 'value' => 'del'),
			array('platform_id' => 11, 'name' => 'CAT', 'value' => 'type'),
			array('platform_id' => 11, 'name' => 'LS', 'value' => 'dir'),
			array('platform_id' => 11, 'name' => 'RM', 'value' => 'del'),
			array('platform_id' => 12, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 12, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 12, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 12, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 12, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 12, 'name' => 'RM', 'value' => '/bin/rm'),
			array('platform_id' => 13, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 13, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 13, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 13, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 13, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 13, 'name' => 'RM', 'value' => '/bin/rm'),

			array('platform_id' => 14, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 14, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 14, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 14, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 14, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 14, 'name' => 'RM', 'value' => '/bin/rm'),

			array('platform_id' => 15, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 15, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 15, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 15, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 15, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 15, 'name' => 'RM', 'value' => '/bin/rm'),

			array('platform_id' => 16, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 16, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 16, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 16, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 16, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 16, 'name' => 'RM', 'value' => '/bin/rm'),

			array('platform_id' => 17, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 17, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 17, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 17, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 17, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 17, 'name' => 'RM', 'value' => '/bin/rm'),
			array('platform_id' => 18, 'name' => 'TYPE', 'value' => '/bin/cat'),
			array('platform_id' => 18, 'name' => 'DIR', 'value' => '/bin/ls -l'),
			array('platform_id' => 18, 'name' => 'DEL', 'value' => '/bin/rm'),
			array('platform_id' => 18, 'name' => 'CAT', 'value' => '/bin/cat'),
			array('platform_id' => 18, 'name' => 'LS', 'value' => '/bin/ls'),
			array('platform_id' => 18, 'name' => 'RM', 'value' => '/bin/rm'),
		),
		'usr' => array(
			array('username' => '_system', 'password' => 'x', 'method' => 'Locked','', '','N'),
			array('username' => 'root',    'password' => '2d941a17bb17b6b398e650642c540d8b1ee42aebb91204d50499a8516a146f98', 'method' => 'Local', '', '','Y'),
		),
		'pref' => array(
			array('user_id' => 1,'name' => 'artifact_store_uri',       'value' => 'db://base64'),
			array('user_id' => 1,'name' => 'auth_login_driver',        'value' => 'auth_local'),
			array('user_id' => 1,'name' => 'bridge_connect_timeout',   'value' => '20'),
			array('user_id' => 1,'name' => 'bridge_read_timeout',      'value' => '300'),
			array('user_id' => 1,'name' => 'bridge_write_timeout',     'value' => '300'),
			array('user_id' => 1,'name' => 'case_sensitive_config_expansion','value' => 'n'),
			array('user_id' => 1,'name' => 'config_process_keep_time', 'value' => '3600'),
			array('user_id' => 1,'name' => 'date_format',              'value' => 'D M j h:ia'),
			array('user_id' => 1,'name' => 'dashboard_instance_age',   'value' => '30'),
			array('user_id' => 1,'name' => 'dashboard',                'value' => 'launchpad'),
			array('user_id' => 1,'name' => 'default_domain',           'value' => 'yourhost.com'),
			array('user_id' => 1,'name' => 'default_user_role',        'value' => ''),
			array('user_id' => 1,'name' => 'engine_life_actions',      'value' => '100'),
			array('user_id' => 1,'name' => 'engine_life_hr',           'value' => '24'),
			array('user_id' => 1,'name' => 'engine_tick_sec',          'value' => '3'),
			array('user_id' => 1,'name' => 'engine_watchdog_sec',      'value' => '5'),
			array('user_id' => 1,'name' => 'engine_zombie_check',      'value' => '3000'),
			array('user_id' => 1,'name' => 'ignore_smtp_send_errors',  'value' => 'n'),
			array('user_id' => 1,'name' => 'items_per_page',           'value' => '20'),
			array('user_id' => 1,'name' => 'lang',                     'value' => 'eng'),
			array('user_id' => 1,'name' => 'lock_timeout',             'value' => '120'),
			array('user_id' => 1,'name' => 'log_date_format',          'value' => 'H:i:s'),
			array('user_id' => 1,'name' => 'mail_from',                'value' => 'root@yourhost.com'),
			array('user_id' => 1,'name' => 'mail_smtp_authpass',       'value' => ''),
			array('user_id' => 1,'name' => 'mail_smtp_authuser',       'value' => ''),
			array('user_id' => 1,'name' => 'mail_smtp_helo',           'value' => ''),
			array('user_id' => 1,'name' => 'mail_smtp_port',           'value' => '25'),
			array('user_id' => 1,'name' => 'mail_smtp_server',         'value' => 'localhost'),
			array('user_id' => 1,'name' => 'mail_smtp_timeout',        'value' => '30'),
			array('user_id' => 1,'name' => 'no_logins_message',        'value' => ''),
			array('user_id' => 1,'name' => 'pre_login_message',        'value' => ''),
			array('user_id' => 1,'name' => 'product_version',          'value' => '4.8.00.00'),
			array('user_id' => 1,'name' => 'show_api_detail',          'value' => 'n'),
			array('user_id' => 1,'name' => 'signoff_reminder_days',    'value' => '1'),
			array('user_id' => 1,'name' => 'show_transfer_percentage', 'value' => 'n'),
			array('user_id' => 1,'name' => 'solid_toc_has_dirs',       'value' => 'n'),
			array('user_id' => 1,'name' => 'store_actions_in_instance','value' => 'n'),
			array('user_id' => 1,'name' => 'store_block_size',         'value' => '32767'),
			array('user_id' => 1,'name' => 'transfer_block_size',      'value' => '16384'),
			array('user_id' => 1,'name' => 'tz',                       'value' => 'America/Chicago'),
			array('user_id' => 1,'name' => 'auto_logout_minutes',	   'value' => '1440'),
			array('user_id' => 1,'name' => 'add_instance_user_info',   'value' => 'n'),
			array('user_id' => 1,'name' => 'semaphore_default_lifespan_hr',   'value' => '24')
		),
		// If you add any Categories HERE you MUST update the win_generate_oracle_pre_post file in App.
		'ap_categories' => array(
			array('id' => 1,'name' => 'Main Tabs'),
			array('id' => 2,'name' => 'Definition Activities'),
			array('id' => 3,'name' => 'Topology Activities'),
			array('id' => 4,'name' => 'Deployment Activities'),
			array('id' => 5,'name' => 'Configuration Activities'),
			array('id' => 6,'name' => 'Reporting Activities'),
			array('id' => 7,'name' => 'Scheduling Activities'),
//			array('id' => 8,'name' => 'Visualizer'),
			array('id' => 9,'name' => 'Other'),
		),
		'access_paths' => array(
			array('ap_category_id' => '1', 'name' => 'Define Tab Visible',     'paths' => 'tab.Define,workbench',    'parent_id' => 0),
			array('ap_category_id' => '1', 'name' => 'Deploy Tab Visible',     'paths' => 'tab.Deploy,delivery',    'parent_id' => 0),
			array('ap_category_id' => '1', 'name' => 'Schedule Tab Visible',   'paths' => 'tab.Schedules,scheds', 'parent_id' => 0),
			array('ap_category_id' => '1', 'name' => 'Report Tab Visible',     'paths' => 'tab.Report,report',    'parent_id' => 0),
			array('ap_category_id' => '1', 'name' => 'Topology Tab Visible',   'paths' => 'tab.Topology,topo',  'parent_id' => 0),
			array('ap_category_id' => '1', 'name' => 'Config Tab Visible',     'paths' => 'tab.Config,config',    'parent_id' => 0),
//			array('ap_category_id' => '1', 'name' => 'Visualizer Tab Visible', 'paths' => 'tab.Visual',    'parent_id' => 0),
		),
		'modules' => array(
			array('platform_id' => 5, 'name' => 'amazonec2_vm', 'version' => 3, 'md5' => '3b6d305675c9a064abb5503e7a1df972'),
			array('platform_id' => 5, 'name' => 'hyperv_vm', 'version' => 3, 'md5' => '03f6bfde007a5bd55deb7116ea350f8a'),
			array('platform_id' => 5, 'name' => 'generic_vm', 'version' => 2, 'md5' => '600cfd74b88a9cdac5b67641bfcd450d'),
			array('platform_id' => 5, 'name' => 'vmware_esx', 'version' => 2, 'md5' => 'df5cc66fc6abf267d54280e68374d011'),
			array('platform_id' => 5, 'name' => 'vmware_center', 'version' => 2, 'md5' => '5032eea3d849d8e386433dc52b776c9d'),
			array('platform_id' => 5, 'name' => 'vmware_vclm', 'version' => 2, 'md5' => 'f556190a709f036c7b99cf74a776d5d5'),
			array('platform_id' => 2, 'name' => 'channel_process_check', 'version' => 1, 'md5' => 'ebc934c4e7cdafaade1b04f1609b54c8'),
			array('platform_id' => 2, 'name' => 'command', 'version' => 6, 'md5' => '0bf17df59a9c6e349a82db8ed2c8e653'),
			array('platform_id' => 2, 'name' => 'config_get', 'version' => 2, 'md5' => '033295a9f96a6dce895186d9fc47c4f5'),
			array('platform_id' => 2, 'name' => 'config_set', 'version' => 2, 'md5' => '749409a84a7a73b74e04308fd6168ba6'),
			array('platform_id' => 2, 'name' => 'delete_file', 'version' => 2, 'md5' => '4b5112f2f62cde4247a33dcfdb477bf4'),
			array('platform_id' => 2, 'name' => 'delete_tree', 'version' => 2, 'md5' => '65ebb11ce97cffad9087c3be1ec0192b'),
			array('platform_id' => 2, 'name' => 'file_copy', 'version' => 1, 'md5' => '24b936010e309695fcad4d432ea47cf9'),
			array('platform_id' => 2, 'name' => 'file_get', 'version' => 8, 'md5' => 'e793f27a047206a32b64db11b5b701b3'),
			array('platform_id' => 2, 'name' => 'file_put_named', 'version' => 3, 'md5' => '53c7f37cb7135a8c0892a4d9c392c64f'),
			array('platform_id' => 2, 'name' => 'file_put', 'version' => 7, 'md5' => 'c98052a6d6f150d4351d9eb25bf8f36c'),
			array('platform_id' => 2, 'name' => 'mkdir', 'version' => 3, 'md5' => 'cf1201389438d08cfd24619568a94913'),
			array('platform_id' => 2, 'name' => 'manual_task', 'version' => 1, 'md5' => 'a4a360393d09de585cc28d3bc095a0d3'),
			array('platform_id' => 2, 'name' => 'promote', 'version' => 2, 'md5' => '67a28dc77dd3031002e031aa88326cb0'),
			array('platform_id' => 2, 'name' => 'remote_action', 'version' => 5, 'md5' => 'a425e2fd8a74a615c1988fd208d4e6ec'),
			array('platform_id' => 2, 'name' => 'restart_last_fail', 'version' => 1, 'md5' => '3ca5245ccc844fd499d247c1728df8c4'),
			array('platform_id' => 2, 'name' => 'run_action', 'version' => 4, 'md5' => 'da06a3655803e3ca42e4ff511266d83a'),
			array('platform_id' => 2, 'name' => 'put_action', 'version' => 2, 'md5' => 'e1d4039d12ff18f018e4d9c06063e3e9'),
			array('platform_id' => 2, 'name' => 'send_notification', 'version' => 3, 'md5' => '144cf20563a16a6ea8ad97c170d19946'),
			array('platform_id' => 2, 'name' => 'sleep', 'version' => 1, 'md5' => 'bb11851a074638f5becc50bfcbdb70a4'),
			array('platform_id' => 2, 'name' => 'suspend', 'version' => 4, 'md5' => '386d493435f226a673a09bd80ac842b3'),
			array('platform_id' => 2, 'name' => 'store_ftp', 'version' => 1, 'md5' => 'd007c3d441188fd34c5888102a56a8c3'),
			array('platform_id' => 2, 'name' => 'store_file', 'version' => 1, 'md5' => '4039992b9977e43264bf9ae47a34a63a'),
			array('platform_id' => 2, 'name' => 'store_webdav', 'version' => 1, 'md5' => '6fe682b293b23799ae12e0b53a72100b'),
			array('platform_id' => 1, 'name' => 'asset_file', 'version' => 2, 'md5' => 'a8cfe859e04744bee5cd069a859f6738'),
			array('platform_id' => 1, 'name' => 'asset_q', 'version' => 1, 'md5' => 'd8687026dc338ac354f59a8475db4b0e'),
			array('platform_id' => 1, 'name' => 'asset_action', 'version' => 2, 'md5' => 'daef377821ee981558ce948213fda91e'),
			array('platform_id' => 1, 'name' => 'asset_null', 'version' => 1, 'md5' => '46f2bd25451c028290358343dd064b95'),
			array('platform_id' => 6, 'name' => 'auth_ldap', 'version' => 7, 'md5' => '9895d876df039be5438295b3db38e71c'),
			array('platform_id' => 6, 'name' => 'auth_local', 'version' => 5, 'md5' => '8329714f7cd76a05e76823ae3b5e512e'),
			array('platform_id' => 6, 'name' => 'auth_msad', 'version' => 12, 'md5' => 'd29b17056e9c9a777d5cd0f9cef1a773'),
			array('platform_id' => 6, 'name' => 'auth_msad_mld', 'version' => 2, 'md5' => '4f6ac80bc49d453e468bb2af6d6dbd0f'),
			array('platform_id' => 6, 'name' => 'auth_msad_sso', 'version' => 5, 'md5' => 'cddc225927275f857aec476fcaca89c4'),
			array('platform_id' => 7, 'name' => 'f5_lb', 'version' => 2, 'md5' => 'f3c3b94f66564fe113cc479bc8a9be53'),
			array('platform_id' => 7, 'name' => 'generic_lb', 'version' => 1, 'md5' => '41bdab238065d4143bb1ba4f38eb3ed6'),
			array('platform_id' => 7, 'name' => 'netscalar_lb', 'version' => 1, 'md5' => 'd8be2853f76dcedfef6dabcfd68b9b65'),
			array('platform_id' => 8, 'name' => 'config_generic', 'version' => 4, 'md5' => '8334c3208b7192c6cc2d401cbe55e130'),
			array('platform_id' => 4, 'name' => 'instance_property', 'version' => 6, 'md5' => '14695c86db0dcb275aab8d90e0f6a340'),
			array('platform_id' => 4, 'name' => 'instance_config', 'version' => 6, 'md5' => '6cb08ce0121f79ec73fa98bec4f035d5'),
			array('platform_id' => 4, 'name' => 'send_path_translator', 'version' => 3, 'md5' => '9e6ed489aec6acfb1ea8fbcbef971c7b'),
			array('platform_id' => 4, 'name' => 'solid_path_translator', 'version' => 13, 'md5' => '8c57ea977425ec41891944510f961ef3'),
			array('platform_id' => 4, 'name' => 'reference_explode', 'version' => 14, 'md5' => '8c38e59cd15a73038f91da5ccc9a6af7'),
			array('platform_id' => 4, 'name' => 'reference_explode_zip', 'version' => 12, 'md5' => 'c3d83ebae7704f12f83c23f8db9275a6'),
			array('platform_id' => 4, 'name' => 'reference_extract', 'version' => 10, 'md5' => '33828c026c25565ad9b1bf7c25620444'),
			array('platform_id' => 4, 'name' => 'reference_delete', 'version' => 3, 'md5' => 'f572b74aaa0b330c5f4a5d23ecc6d6ca'),
			array('platform_id' => 4, 'name' => 'reference_md', 'version' => 3, 'md5' => 'b1754881fe0da824d46f2c56b7f7df3e'),
			array('platform_id' => 4, 'name' => 'warfile_content', 'version' => 6, 'md5' => 'd7721ec584c55754c7197dfedb9b094b'),
			array('platform_id' => 9, 'name' => 'archive_audit_log', 'version' => 1, 'md5' => '2c7cb52248af6c6f3c8cf02678484481'),
			array('platform_id' => 9, 'name' => 'deploy_package', 'version' => 3, 'md5' => '027cd9b7998988ca9d12f0eba97f341e'),
			array('platform_id' => 9, 'name' => 'deploy_package_conditional', 'version' => 2, 'md5' => '3876759a1280e2d6710484624ac27390'),
			array('platform_id' => 9, 'name' => 'deploy_repo', 'version' => 1, 'md5' => '753bac958a26a1b679945077fe346b99'),
			array('platform_id' => 9, 'name' => 'expire_instance', 'version' => 3, 'md5' => '81e7439502cb9e080aee592779560eeb'),
			array('platform_id' => 9, 'name' => 'garbage_collector', 'version' => 2, 'md5' => '47b28580b9260d5864083bf770aee322'),
			array('platform_id' => 9, 'name' => 'prune_channel_rev', 'version' => 1, 'md5' => '0520d00602ea2ce5af62869fc966c6f6'),
			array('platform_id' => 9, 'name' => 'prune_instance_data', 'version' => 3, 'md5' => '9aacace3547099542702728bc2750451'),
			array('platform_id' => 9, 'name' => 'prune_instance_feed', 'version' => 1, 'md5' => '50ca6fa69e8f315915609a59a961694f'),
			array('platform_id' => 9, 'name' => 'prune_task_feed', 'version' => 1, 'md5' => '44ecb2daba864d0ecc6f61615554d455'),
			array('platform_id' => 9, 'name' => 'prune_shared_drive', 'version' => 1, 'md5' => 'd41d8cd98f00b204e9800998ecf8427e'),
			array('platform_id' => 9, 'name' => 'purge_system_process', 'version' => 1, 'md5' => 'c9dfaa65fd10ec8c5ce0c34ee447233c'),
			array('platform_id' => 9, 'name' => 'sync_all_blueprint', 'version' => 2, 'md5' => '33f339aa07604e1ace3fe3176440fc63'),
			array('platform_id' => 9, 'name' => 'sync_blueprint', 'version' => 2, 'md5' => 'b789cc31057cc51fdaf2b9729dac1396'),
			array('platform_id' => 9, 'name' => 'system_stat', 'version' => 2, 'md5' => '9b141ac4ea9ce61a207f785df76caffa'),
			array('platform_id' => 8, 'name' => 'config_apache_2', 'version' => 9, 'md5' => 'd3c2bfdc19e7bbe94bce8840770f3ac5'),
			array('platform_id' => 8, 'name' => 'config_db2', 'version' => 3, 'md5' => '0daa71e09bf24d29e1fbe080486cee4c'),
			array('platform_id' => 8, 'name' => 'config_glassfish_3', 'version' => 3, 'md5' => '8b61bbc2055efa96b3400529783f83db'),
			array('platform_id' => 8, 'name' => 'config_ibm_mq', 'version' => 1, 'md5' => '4d876a24e5a44f4cb2e28dba5070dab2'),
			array('platform_id' => 8, 'name' => 'config_iis_6', 'version' => 6, 'md5' => '0c40090ea2e25319aa3e3555b251336f'),
			array('platform_id' => 8, 'name' => 'config_iis_7', 'version' => 7, 'md5' => 'a489679243bb002d54bd7884fd70d262'),
			array('platform_id' => 8, 'name' => 'config_jboss_5', 'version' => 10, 'md5' => '2b68cf7deb2a4b7a084549957626a829'),
			array('platform_id' => 8, 'name' => 'config_jboss_6', 'version' => 4, 'md5' => '5fa8f1c55d2af1360c90c821309b73c8'),
			array('platform_id' => 8, 'name' => 'config_mysql_5', 'version' => 11, 'md5' => '542abcc40f86e1188dce2d47a0a90cfe'),
			array('platform_id' => 8, 'name' => 'config_oracle_11g', 'version' => 7, 'md5' => 'a25096e9876927217e828707cf697a38'),
			array('platform_id' => 8, 'name' => 'config_php_5', 'version' => 6, 'md5' => '558b6d50a3735c679c7c7853e3359af5'),
			array('platform_id' => 8, 'name' => 'config_sqlserver_2008', 'version' => 6, 'md5' => '954bbe78f9664e92a8594a23b61ec13a'),
			array('platform_id' => 8, 'name' => 'config_sharepoint_2007', 'version' => 1, 'md5' => '0ea817630bd8076bbda280475e46ec95'),
			array('platform_id' => 8, 'name' => 'config_sharepoint_2010', 'version' => 1, 'md5' => 'fbf918ee39375fe502e8802c62d85a32'),
			array('platform_id' => 8, 'name' => 'config_tibco_bw', 'version' => 5, 'md5' => 'ea1acf5f57b41d52e073dff31777fac4'),
			array('platform_id' => 8, 'name' => 'config_tomcat_6', 'version' => 6, 'md5' => '43cd8fd1043dd8f92dce9655871f6780'),
			array('platform_id' => 8, 'name' => 'config_tomcat_7', 'version' => 6, 'md5' => '85951ba44f69976c4a416b8f16d567a4'),
			array('platform_id' => 8, 'name' => 'config_weblogic_10', 'version' => 12, 'md5' => '225a25d4f3779aad2fac7d1f48bb5efb'),
			array('platform_id' => 8, 'name' => 'config_websphere_6', 'version' => 9, 'md5' => '15374b3e9784c319e65dd897b148aea0'),
			array('platform_id' => 8, 'name' => 'config_websphere_7', 'version' => 7, 'md5' => '076699b8ab7a8e73520c08cf3741c626'),
			array('platform_id' => 8, 'name' => 'config_websphere_8', 'version' => 4, 'md5' => '856b53b5c4570721e3e86e1c61009203'),
		),
		'handler_roles' => array(
			array('handler_id' => 1, 'role_id' => 0),
		),
);
